### ISSUE TITLE
AlertListener does not work with some hosts on Linux

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/Themerr-plex#143]
### Describe the Bug

Plex alert listener fails to start on Linux (when using ipv6?) and the following error appears in the logs.

`ERROR (alert:94) - getsockaddrarg: bad family`

### Additional Context

IPv6 is likely disabled in Plex's python build.

We can possibly patch python-plexapi to setup websocket-client properly. https://github.com/ReenigneArcher/python-plexapi/blob/c41d98170b3761b8edc7d75970a01b80bb6281c6/plexapi/alert.py#L55

https://websocket-client.readthedocs.io/en/v0.59.0/examples.html?highlight=socket#using-unix-domain-sockets

https://github.com/majek/puka/issues/27

https://github.com/qpython-android/qpysl4a/issues/2

**Comment by garlik82** [comment]
Getting this error, but I have ipv6 disabled everywhere. Running Plex on a Synology NAS, not under docker.

**Comment by ReenigneArcher** [comment]
@garlik82 I submitted a PR to address this in python plexapi, but unfortunately I don't think it will work in Python 2.7.

But yes, I now think it's an issue on (some) unix devices.

**Comment by garlik82** [comment]
No way around it then?

**Comment by ReenigneArcher** [comment]
Not at this time, but next version will not require the alert listener at least.

**Comment by garlik82** [comment]
Hit me up when you have a version to test. Thank you for your work.

**Comment by ReenigneArcher** [comment]
@garlik82 you can try nightly. Alert listener won't work but there is now a scheduled task option.

**Comment by garlik82** [comment]
> @garlik82 you can try nightly. Alert listener won't work but there is now a scheduled task option.

How do I trigger that task?

**Comment by garlik82** [comment]
I must be doing something wrong. I see no errors in the log but I also don't get any themes.
[dev.lizardbyte.themerr-plex.log](https://github.com/LizardByte/Themerr-plex/files/12717133/dev.lizardbyte.themerr-plex.log)

**Comment by ReenigneArcher** [comment]
Please reach out on our discord. https://app.lizardbyte.dev/discord

**Comment by Shawn9347** [comment]
> Not at this time, but next version will not require the alert listener at least.

By next version you mean the next version of Themerr?

**Comment by zdimension** [comment]
This can be fixed by using 127.0.0.1 instead of localhost as Plex's URL in plex_api_helper.py. The error comes from the fact that localhost resolves to ::1 by default on many Linux distros, but the WS API expects an IPv4-family address.

**Comment by ReenigneArcher** [comment]
@zdimension Thanks for that info! I will put up a "fix" once plexapi is updated on pypi after https://github.com/pkkid/python-plexapi/pull/1281.

**Comment by Shawn9347** [comment]
> This can be fixed by using 127.0.0.1 instead of localhost as Plex's URL in plex_api_helper.py. The error comes from the fact that localhost resolves to ::1 by default on many Linux distros, but the WS API expects an IPv4-family address.

I can confirm that this works. Awesome. Thank you.
