### ISSUE TITLE
Custom Collections show up in Web UI

### ISSUE THREAD

**Issue by jjnether** [LizardByte/Themerr-plex#254]
### Describe the Bug

When navigating the Web UI, custom collections will not only show up, but will show a theme is missing and will have the option to add a theme. If you hit add, it will route to the DB page with a generic TMDB website autopopulated (https://www.themoviedb.org/collection/)

### Expected Behavior

Not sure if we want custom collections to show up, but at the very least, there shouldn't be an option to add a theme for them. It also maybe shouldn't indicate that a theme is missing from them.

**Comment by x1ao4** [comment]
Actually, is there a way to add theme songs to custom collections? I know this isn't a feature provided by Themerr, but I would like to be able to add theme songs to my custom collections myself. Is this possible? Alternatively, could Themerr add a feature to allow adding local music files to custom collections?

**Comment by ReenigneArcher** [comment]
@x1ao4 the only way to add themes to collections is via the rest API.

We can possibly look at adding a way to do this after authentication is added to the UI.

**Comment by ReenigneArcher** [comment]
How does your script work? It might be worth incorporating into Themerr

**Comment by x1ao4** [comment]
```
import os
import configparser
import plexapi.server
from pathlib import Path

def setup_plexapi(config_file):
    """
    创建 Plex 服务器对象。
    """
    # 从 config.ini 文件中读取 Plex 服务器的地址和 token
    config = configparser.ConfigParser()
    config.read(config_file)
    plex_url = config.get('server', 'address')
    plex_token = config.get('server', 'token')

    plex_server = plexapi.server.PlexServer(baseurl=plex_url, token=plex_token)
    return plex_server

def upload_theme_to_collection(plex_server, collection_name, theme_path):
    """
    为指定的合集上传主题曲。
    """
    # 获取所有的合集
    collections = plex_server.library.all(libtype='collection')
    # 查找指定的合集
    for collection in collections:
        if collection.title == collection_name:
            # 上传主题曲
            collection.uploadTheme(filepath=theme_path)
            print(f"已成功为合集 {collection_name} 上传主题曲。")
            return
    print(f"未找到名为 {collection_name} 的合集。")

def main():
    # 定义配置文件路径
    config_file = Path(__file__).parent / 'config.ini'

    # 设置 Plex 服务器
    plex_server = setup_plexapi(config_file)

    # 提示用户输入合集名称和音频文件路径
    collection_name = input("请输入合集名称：")
    theme_path = input("请输入音频文件路径：")

    # 上传主题曲
    upload_theme_to_collection(plex_server, collection_name, theme_path)

if __name__ == "__main__":
    main()

```

I've only implemented the functionality for collection theme songs, but similar methods could be applied for other types of theme songs. You can consider integrating them directly into Themerr.

**Comment by ReenigneArcher** [comment]
Oh okay, you're having python ask for user input. Interesting.

**Comment by x1ao4** [comment]
Yes, because this is a standalone script.

Could you consider adding this feature to Themerr? This way, users can not only add theme songs from YouTube but also choose to upload theme songs from their local files to ThemerrDB. Additionally, they could directly add local theme songs to their custom collections or other items from the Themerr WebUI.

**Comment by ReenigneArcher** [comment]
> Could you consider adding this feature to Themerr?

Maybe. I think the authentication PR needs to be added first. That's waiting on adding unit testing if you have any ideas.
