### ISSUE TITLE
There seems to be an anomaly in the display of the status

### ISSUE THREAD

**Issue by x1ao4** [LizardByte/Themerr-plex#397]
### Describe the Bug

I noticed that only the library ranked first in the WebUI displays "Themerr provided" for items with theme songs, while all other libraries, except for those with theme songs provided by Plex, show "Unknown provider" for items with theme songs (Collections will display "Themerr provided"). Additionally, the same movie appears as "Themerr provided" in the first library but as "Unknown provider" in others. This seems to be an issue.

<img width="1403" alt="Unknown provider" src="https://github.com/LizardByte/Themerr-plex/assets/112841659/ce5ce90a-3a43-40f2-b4fb-41ba18c02110">

Shouldn't all movie theme songs be provided by Themerr? I'm not quite understanding the scenarios in which "Unknown provider" and "User provided" appear.

Moreover, I'm curious about how the libraries are sorted in the WebUI. When the library names are in Chinese, I haven't been able to discern a consistent sorting pattern.

**Comment by ReenigneArcher** [comment]
Did you use Themerr before v0.3?

**Comment by x1ao4** [comment]
> Did you use Themerr before v0.3?

Yes, I've used v0.1.3 before.

**Comment by ReenigneArcher** [comment]
There's a setting to migrate themes, and if that doesn't work there's another setting to ignore locked themes.

Note, that it can take an hour or so to get a new UI.

Regarding the sorting, it's just how it's returned from Plex.

**Comment by x1ao4** [comment]
> There's a setting to migrate themes, and if that doesn't work there's another setting to ignore locked themes.

I'll give it a try.


> Regarding the sorting, it's just how it's returned from Plex.

In Plex's "Manage - Libraries," the libraries are sorted as all movie libraries, all TV show libraries, all music libraries, and all photo libraries. Within each category, they are sorted based on the Unicode encoding of characters. However, in Themerr's WebUI, my library sorting appears as movie library, TV show library, movie library, TV show library, movie library, TV show library, movie library, TV show library, alternating in this manner, and they are not sorted according to Unicode encoding order, which is strange.

**Comment by ReenigneArcher** [comment]
The libraries are likely in the order they were created, those are by section id.

**Comment by x1ao4** [comment]
No, the IDs of the top four libraries in Themerr WebUI are 140, 46, 2, and 104, which is obviously not the order of library establishment, and I cannot find any patterns.

**Comment by ReenigneArcher** [comment]
It's generated here: https://github.com/LizardByte/Themerr-plex/blob/19573c19cc5a2c954feb4a470d7376c29666e581/Contents/Code/webapp.py#L198

There's no ordering performed, it's just in the order given to us by the Plex api.

**Comment by x1ao4** [comment]
> There's a setting to migrate themes

It worked.
